/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JOptionPane;

/**
 *
 * @author Patrick
 */
public class AccountGUI extends javax.swing.JFrame {

    /**
     * Creates new form AccountGUI
     */
    
    Account acc;
    public AccountGUI() {
        initComponents();
        acc = new Account();
        liUser.setModel(acc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmAddUser = new javax.swing.JPopupMenu();
        miaddUser = new javax.swing.JMenuItem();
        miperformAccTest = new javax.swing.JMenuItem();
        pmAccount = new javax.swing.JPopupMenu();
        micreateAcc = new javax.swing.JMenuItem();
        lbMoney = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        liUser = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        taOutput = new javax.swing.JTextArea();

        miaddUser.setText("add user");
        miaddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onAddUser(evt);
            }
        });
        pmAddUser.add(miaddUser);

        miperformAccTest.setText("perform account test");
        miperformAccTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onAccountTest(evt);
            }
        });
        pmAddUser.add(miperformAccTest);

        micreateAcc.setText("create new account");
        micreateAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCreateAccount(evt);
            }
        });
        pmAccount.add(micreateAcc);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kontoverwaltung");
        setPreferredSize(new java.awt.Dimension(450, 350));

        lbMoney.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbMoney.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbMoney.setText("0,00 Euro");
        lbMoney.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lbMoney.setBorder(javax.swing.BorderFactory.createTitledBorder("Account"));
        lbMoney.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lbMoney.setMaximumSize(new java.awt.Dimension(46, 50));
        lbMoney.setMinimumSize(new java.awt.Dimension(46, 50));
        lbMoney.setPreferredSize(new java.awt.Dimension(46, 50));
        getContentPane().add(lbMoney, java.awt.BorderLayout.SOUTH);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(110, 130));

        liUser.setBorder(javax.swing.BorderFactory.createTitledBorder("User"));
        liUser.setComponentPopupMenu(pmAddUser);
        liUser.setMaximumSize(new java.awt.Dimension(110, 120));
        liUser.setMinimumSize(new java.awt.Dimension(80, 103));
        liUser.setPreferredSize(new java.awt.Dimension(40, 103));
        jScrollPane1.setViewportView(liUser);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.LINE_START);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        taOutput.setColumns(20);
        taOutput.setRows(5);
        taOutput.setBorder(javax.swing.BorderFactory.createTitledBorder("Log-output"));
        taOutput.setComponentPopupMenu(pmAccount);
        taOutput.setMaximumSize(new java.awt.Dimension(1700, 2147483647));
        taOutput.setMinimumSize(new java.awt.Dimension(500, 43));
        taOutput.setPreferredSize(new java.awt.Dimension(1000, 115));
        jScrollPane2.setViewportView(taOutput);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onAddUser(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onAddUser
        try{
            String name = JOptionPane.showInputDialog("Name", "");
            acc.add(name);
            liUser.updateUI();
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
       
    }//GEN-LAST:event_onAddUser

    private void onAccountTest(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onAccountTest
        
        
    }//GEN-LAST:event_onAccountTest

    private void onCreateAccount(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCreateAccount
        double startMoney = 50.00;
        lbMoney.setText(startMoney + " Euro");
    }//GEN-LAST:event_onCreateAccount

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbMoney;
    private javax.swing.JList<String> liUser;
    private javax.swing.JMenuItem miaddUser;
    private javax.swing.JMenuItem micreateAcc;
    private javax.swing.JMenuItem miperformAccTest;
    private javax.swing.JPopupMenu pmAccount;
    private javax.swing.JPopupMenu pmAddUser;
    private javax.swing.JTextArea taOutput;
    // End of variables declaration//GEN-END:variables
}
